apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Using the :latest tag prevents reproducible rollbacks.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Image tag ':latest' or missing tag is not allowed."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ `{{ element.image }}` }}"
                    operator: AnyIn
                    value: ["*:latest"]
                  - key: "{{ `{{ element.image }}` }}"
                    operator: AnyNotIn
                    value: ["*:*"]
          - list: "request.object.spec.initContainers || `[]`"
            deny:
              conditions:
                any:
                  - key: "{{ `{{ element.image }}` }}"
                    operator: AnyIn
                    value: ["*:latest"]
                  - key: "{{ `{{ element.image }}` }}"
                    operator: AnyNotIn
                    value: ["*:*"]
          - list: "request.object.spec.ephemeralContainers || `[]`"
            deny:
              conditions:
                any:
                  - key: "{{ `{{ element.image }}` }}"
                    operator: AnyIn
                    value: ["*:latest"]
                  - key: "{{ `{{ element.image }}` }}"
                    operator: AnyNotIn
                    value: ["*:*"]
