version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/src/Pi3"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/src/Pi4"
    schedule:
      interval: "weekly"
