apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-user-password
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-user-password
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: authentik-user
        password: "{{ .db_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: authentik-config
        property: db-password
