{
 "title": "Hausnetz Switches",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "site",
    "query": {
     "query": "label_values(up{job=\"network_switches\"}, site)"
    }
   },
   {
    "name": "instance",
    "label": "Switch",
    "query": {
     "query": "label_values(up{job=\"network_switches\", site=~\"$site\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "port",
    "query": {
     "query": "query_result(label_join(count by (ifName, ifAlias) (ifHCInOctets{instance=~\"$instance\"}), \"port_desc\", \" - \", \"ifName\", \"ifAlias\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tpSysMonitorCpu5Minutes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tpSysMonitorMemoryUtilization{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports Admin Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ifOperStatus{instance=~\"$instance\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports Admin Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ifAdminStatus{instance=~\"$instance\"} == 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${port} ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "repeat": "port",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{instance=~\"$instance\", ifName=~\"$port\"}[10m]) * 8",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(ifHCOutOctets{instance=~\"$instance\", ifName=~\"$port\"}[10m]) * 8",
     "legendFormat": "Outbound"
    },
    {
     "expr": "rate(ifInErrors{instance=~\"$instance\", ifName=~\"$port\"}[10m])",
     "legendFormat": "Inbound Errors"
    },
    {
     "expr": "rate(ifOutErrors{instance=~\"$instance\", ifName=~\"$port\"}[10m])",
     "legendFormat": "Outbound Errors"
    },
    {
     "expr": "(ifHighSpeed{instance=~\"$instance\", ifName=~\"$port\"} * 1000000) \nand on(instance, ifName) \n(\n  (\n    (rate(ifHCInOctets{instance=~\"$instance\", ifName=~\"$port\"}[4m]) * 8) \n    / on(instance, ifName) \n    (ifHighSpeed{instance=~\"$instance\", ifName=~\"$port\"} * 1000000)\n  ) > 0.04\n)",
     "legendFormat": "Max Capacity"
    }
   ]
  }
 ]
}