{{- $poolerMode := "shared" -}}
{{- with .Values.crossplane -}}
{{- $poolerMode = default "shared" .poolerMode -}}
{{- end }}
{{- if and (ne $poolerMode "shared") (ne $poolerMode "dedicated") -}}
{{- fail "crossplane.poolerMode must be either 'shared' or 'dedicated'" -}}
{{- end }}
apiVersion: database.lippok.dev/v1alpha1
kind: PostgresDatabase
metadata:
  name: authentik-db
spec:
  {{- if eq $poolerMode "dedicated" }}
  compositionRef:
    name: postgresdatabase-sql-dedicated
  {{- end }}
  parameters:
    databaseName: authentik-db
    roleName: authentik-user
    createDb: true
    deletionPolicy: Delete
  writeConnectionSecretToRef:
    name: authentik-db-conn
