apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: authentik-config              # K8s secret in secret-store ns (Vault: apps/authentik/config)
        property: secret-key
    - secretKey: argocd-oidc-client-secret
      remoteRef:
        key: argocd-oidc                   # K8s secret in secret-store ns
        property: client-secret
