- Local:
  - Portainer:
      description: Docker Container Management
      href: "https://port.lippok.dev"
      icon: portainer.png
      widget:
        type: portainer
        url: "https://port.lippok.dev"
        env: 1
        key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}

    - Gatus:
      description: Service Monitoring
      href: "https://gatus.lippok.dev"
      icon: gatus.png
      widget:
        type: gatus
        url: "https://gatus.lippok.dev"

  - Traefik:
      description: Reverse Proxy
      href: "https://traefik.lippok.dev"
      icon: traefik.png
      widget:
        type: traefik
        url: "https://traefik.lippok.dev"
        username: {{HOMEPAGE_VAR_TRAEFIK_USER}} 
        password: {{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}

    - Vieta:
      description: Unifi Router Management
      href: "unifi.ui.com"
      icon: vieta.png
      widget:
        type: unifi
        url: 10.10.0.1
        username: {{HOMEPAGE_VAR_UNIFI_USER}}
        password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
        site: Vieta

  - Apollo:
      description: NAS
      href: "https://apollo.lippok.dev"
      icon: apollo.png

- Remote:
  - Mail:
      description: Mail Server
      href: "https://mail.lippok.eu"
      icon: mail.png
      widget:
        type: mailcow
        url: "https://mail.lippok.eu"
        key: {{HOMEPAGE_VAR_MAILCOW_API_KEY}}

  - FritzBox:
      description: Router Management
      href: "https://fb.lippok.dev"
      icon: fritzbox.png
      widget:
        type: fritzbox
        url: http://192.168.178.1

  - Zeus:
      description: Offsite NAS
      href: "https://zeus.lippok.dev"
      icon: zeus.png

- Cloud:
  - Cloudflare:
      description: DNS Management
      href: "https://dash.cloudflare.com"
      icon: cloudflare.png

  - Contabo:
      description: VPS Management
      href: https://my.contabo.com/
      icon: contabo.png
