providers:
  openweathermap: {{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}

title: Olympus
theme: dark
color: slate
headerStyle: boxed
base: olympus.lippok.dev

layout:
  Local:
    header: true
  Remote:
    header: true
  Cloud:
    header: true
