apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-pg-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: crossplane-pg-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cnpg-superuser