apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: gatus-secrets
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: apps/gatus
        property: discord-webhook-url
