replicaCount: 1

image:
  repository: ghcr.io/corentinth/it-tools
  # renovate: datasource=docker depName=ghcr.io/corentinth/it-tools versioning=loose
  tag: 2024.10.22-7ca5933
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: true

nginx:
  errorLogLevel: warn
  accessLog: "off"

service:
  port: 80

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

probes:
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3

httproute:
  enabled: true
  gateway:
    name: main-gateway
    namespace: gateway
  hostnames:
    - it-tools.lippok.dev
