http:
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "{{env "TRAEFIK_USER"}}:{{env "TRAEFIK_PASSWORD"}}"
    
    auth:
      basicAuth:
        users:
          - "{{env "TRAEFIK_USER"}}:{{env "TRAEFIK_PASSWORD"}}"

  routers:
    api:
      rule: "Host(`traefik.lippok.dev`)"
      entrypoints:
       - websecure
      middlewares:
       - dashboard-auth
      service: api@internal
      tls:
        certResolver: letsencrypt

    apollo:
      rule: "Host(`apollo.lippok.dev`)"
      entrypoints:
       - websecure
      service: apollo-service
      tls:
        certResolver: letsencrypt

    fb:
      rule: "Host(`fb.lippok.dev`)"
      entrypoints:
       - websecure
      service: fb-service
      tls:
        certResolver: letsencrypt

    minerva:
      rule: "Host(`minerva.eos.lippok.dev`)"
      entrypoints:
       - websecure
      service: minerva-service
      tls:
        certResolver: letsencrypt

    zeus:
      rule: "Host(`zeus.lippok.dev`)"
      entrypoints:
       - websecure
      service: zeus-service
      tls:
        certResolver: letsencrypt

    uptimekuma:
      rule: "Host(`minerva.eos.lippok.dev`)"
      entrypoints:
        - websecure
      service: uptimekuma-service
      tls:
        certResolver: letsencrypt

  services:
  
    apollo-service:
      loadBalancer:
        servers:
          - url: "http://apollo.athena:5000"

    fb-service:
      loadBalancer:
        servers:
          - url: "http://192.168.178.1:80"

    minerva-service:
      loadBalancer:
        servers:
          - url: "http://pi3.athena:3001"

    zeus-service:
      loadBalancer:
        servers:
          - url: "http://zeus.athena:80"

    uptimekuma-service:
      loadBalancer:
        servers:
          - url: "http://pi3.athena:3001"