apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tailscale-oauth
        metadataPolicy: None
        property: oauth-client-id
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tailscale-oauth
        metadataPolicy: None
        property: oauth-secret
