storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: "Mail Server Lippok"
    group: "Mail Servers"
    url: "icmp://mail.lippok.eu"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Mail Server Lippok HTTPS"
    group: "Mail Servers"
    url: "https://mail.lippok.eu"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 24h"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Mail Server Lippok IMAP"
    group: "Mail Servers"
    url: "tcp://mail.lippok.eu:993"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Mail Server Lippok SMTP"
    group: "Mail Servers"
    url: "tcp://mail.lippok.eu:587"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Apollo NAS"
    group: "NAS"
    url: "https://apollo.lippok.dev"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 24h"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Apollo NAS Ping"
    group: "NAS"
    url: "icmp://apollo.athena"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Olympus Page"
    group: "Web Servers"
    url: "https://olympus.lippok.dev"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 24h"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Portainer"
    group: "Web Servers"
    url: "https://port.lippok.dev"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 24h"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "FritzBox"
    group: "Routers"
    url: "icmp://192.168.178.1"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "FritzBox HTTPS"
    group: "Routers"
    url: "https://fb.lippok.dev"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 24h"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "pi3 Athena"
    group: "Servers"
    url: "icmp://pi3.athena"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "NAS Zeus"
    group: "NAS"
    url: "https://zeus.lippok.dev"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[CONNECTED] == true"
      - "[RESPONSETIME] < 2000"
      - "[CERTIFICATE_EXPIRATION] > 24h"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "NAS Zeus Ping"
    group: "NAS"
    url: "icmp://zeus.athena"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Router Vieta"
    group: "Routers"
    url: "icmp://10.10.0.1"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

  - name: "Router Minerva"
    group: "Routers"
    url: "icmp://10.0.0.1"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        failure-threshold: 3
        success-threshold: 2

alerting:
  discord:
    webhook-url: "${DISCORD_WEBHOOK_URL}"
