kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
        
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 1024Mi
          cpu: 500m
      nodeSelector:
        dedicated: database
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

  alertmanager:
    alertmanagerSpec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
        
      resources:
        requests:
          memory: 50Mi
          cpu: 10m
        limits:
          memory: 100Mi
          cpu: 100m
      nodeSelector:
        dedicated: database
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
                
  grafana:
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
    persistence:
      enabled: false 
    envValueFrom:
      DB_HOST:
        secretKeyRef:
          name: grafana-db-credentials
          key: endpoint
      DB_PORT:
        secretKeyRef:
          name: grafana-db-credentials
          key: port
      DB_USER:
        secretKeyRef:
          name: grafana-db-credentials
          key: username
      DB_PASSWORD:
        secretKeyRef:
          name: grafana-db-credentials
          key: password
      GRAFANA_OIDC_SECRET:
        secretKeyRef:
          name: grafana-oidc-credentials
          key: client-secret

    grafana.ini:
      server:
        domain: grafana.lippok.dev
        root_url: https://grafana.lippok.dev/
        router_logging: false
      database:
        type: postgres
        host: $__env{DB_HOST}:$__env{DB_PORT}
        name: grafana-db
        user: $__env{DB_USER}
        password: $__env{DB_PASSWORD}
        ssl_mode: require
      auth.generic_oauth:
        enabled: true
        name: Authentik
        allow_sign_up: true
        client_id: grafana
        client_secret: $__env{GRAFANA_OIDC_SECRET}
        scopes: openid email profile groups
        auth_url: https://auth.lippok.dev/application/o/authorize/
        token_url: https://auth.lippok.dev/application/o/token/
        api_url: https://auth.lippok.dev/application/o/userinfo/
        role_attribute_path: contains(groups, 'authentik Admins') && 'GrafanaAdmin' || 'Viewer'
      log:
        mode: console
        level: info
        filters: tsdb.loki:warn
