kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
        
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 1024Mi
          cpu: 500m
      nodeSelector:
        dedicated: database
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

  alertmanager:
    alertmanagerSpec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
        
      resources:
        requests:
          memory: 50Mi
          cpu: 10m
        limits:
          memory: 100Mi
          cpu: 100m
      nodeSelector:
        dedicated: database
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
                
  grafana:
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
    persistence:
      enabled: false 
    envValueFrom:
      DB_HOST:
        secretKeyRef:
          name: grafana-db-credentials
          key: endpoint
      DB_PORT:
        secretKeyRef:
          name: grafana-db-credentials
          key: port
      DB_USER:
        secretKeyRef:
          name: grafana-db-credentials
          key: username
      DB_PASSWORD:
        secretKeyRef:
          name: grafana-db-credentials
          key: password
          
    grafana.ini:
      database:
        type: postgres
        host: $__env{DB_HOST}:$__env{DB_PORT}
        name: grafana-db
        user: $__env{DB_USER}
        password: $__env{DB_PASSWORD}
        ssl_mode: require
      server:
        router_logging: false
      log:
        mode: console
        level: info
        filters: tsdb.loki:warn
