{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Site", "label": "Site", "query": "Default \\(default\\)" },
   { "name": "Gateway", "label": "Gateway", "query": "Vieta" },
   { "name": "Smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m" },
   { "name": "GatewayR", "query": "CGU Minerva" },
   { "name": "node", "query": "172.17.0.1:9100" },
   { "name": "job", "query": "node-exporter" },
   { "name": "nodeR", "query": "pi3.athena:9100" },
   { "name": "jobR", "query": "node-exporter-pi3" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; margin-bottom: 20px; font-size: 14px; color: #555; font-style: italic;\">\r\n  Each column represents a different physical site\r\n</div>\r\n\r\n<div style=\"display: flex; width: 100%;\">\r\n  <!-- Left site -->\r\n  <div style=\"width: calc(50% - 1px); text-align: center; padding: 20px;\">\r\n    <h1 style=\"text-align:center;font-size: 5em\">Vieta</h1>\r\n  </div>\r\n\r\n  <!-- Divider -->\r\n  <div style=\"width: 2px; background-color: #ccc;\"></div>\r\n\r\n  <!-- Right site -->\r\n  <div style=\"width: calc(50% - 1px); text-align: center; padding: 20px;\">\r\n    <h1 style=\"text-align:center;font-size: 5em\">Minerva</h1>\r\n  </div>\r\n</div>\r\n"
   }
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unpoller_device_uptime_seconds{name=\"Vieta\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unpoller_device_cpu_utilization_ratio{name=\"Vieta\"}",
     "legendFormat": " CPU %"
    },
    {
     "expr": "unpoller_device_memory_utilization_ratio{name=\"Vieta\"}",
     "legendFormat": " RAM %"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (unpoller_device_uplink_latency_seconds{name=~\"Vieta\"})",
     "legendFormat": "Uplink Latency"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unpoller_remote_device_uptime_seconds{name=~\"$GatewayR\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unpoller_remote_device_cpu_utilization_ratio{name=~\"$GatewayR\"}",
     "legendFormat": " CPU %"
    },
    {
     "expr": "unpoller_remote_device_memory_utilization_ratio{name=~\"$GatewayR\"}",
     "legendFormat": " RAM %"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (unpoller_remote_device_uplink_latency_seconds{name=~\"$GatewayR\"})",
     "legendFormat": "Uplink Latency"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_dsl_noise_margin_dB{friendly_name=\"Fritz!Box\"}",
     "legendFormat": "DSL Noise {{direction}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_device_stations{station_type=\"user\"})",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_remote_device_stations{name=~\"$GatewayR\"})",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "WAN Throughput",
   "type": "timeseries",
   "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(unpoller_device_wan_receive_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Rx"
    },
    {
     "expr": "rate(unpoller_device_wan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Tx"
    }
   ]
  },
  {
   "title": "LAN Throughput",
   "type": "timeseries",
   "description": "Spikes on this graph that do not appear on the WAN graph indicate inter-VLAN-routing. Rx is on the negative axis.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(unpoller_device_lan_receive_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Rx"
    },
    {
     "expr": "rate(unpoller_device_lan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$Gateway\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Tx"
    }
   ]
  },
  {
   "title": "WAN Throughput",
   "type": "timeseries",
   "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(unpoller_remote_device_wan_receive_bytes_total{site_name=~\"$Site\", name=~\"$GatewayR\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Rx"
    },
    {
     "expr": "rate(unpoller_remote_device_wan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$GatewayR\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Tx"
    }
   ]
  },
  {
   "title": "LAN Throughput",
   "type": "timeseries",
   "description": "Spikes on this graph that do not appear on the WAN graph indicate inter-VLAN-routing. Rx is on the negative axis.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(unpoller_remote_device_lan_receive_bytes_total{site_name=~\"$Site\", name=~\"$GatewayR\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Rx"
    },
    {
     "expr": "rate(unpoller_remote_device_lan_transmit_bytes_total{site_name=~\"$Site\", name=~\"$GatewayR\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Tx"
    }
   ]
  },
  {
   "title": "Bandwidth / Devices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", ap_name=~\"Access Point U6\\\\+\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by (name) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", ap_name=~\"Access Point U6\\\\+\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by (name) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", sw_name=~\"(Switch Flex Mini|Vieta)\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by (name) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", sw_name=~\"(Switch Flex Mini|Vieta)\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Bandwidth / Devices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(unpoller_remote_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", ap_name=~\"U6\\\\+\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by (name) (rate(unpoller_remote_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", ap_name=~\"U6\\\\+\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by (name) (rate(unpoller_remote_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", sw_name=~\"CGU Minerva\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by (name) (rate(unpoller_remote_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\".*\", site_name=~\".*\", sw_name=~\"CGU Minerva\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "options": {
    "content": "<h5 style=\"text-align:center;font-size: 3em\">Pi4</h5>\r\n\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "options": {
    "content": "<h5 style=\"text-align:center;font-size: 3em\">Pi3</h5>\r\n\r\n\r\n\r\n"
   }
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$nodeR\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$nodeR\", job=\"$jobR\"} / node_memory_MemTotal_bytes{instance=\"$nodeR\", job=\"$jobR\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$nodeR\",job=\"$jobR\"} - node_memory_SwapFree_bytes{instance=\"$nodeR\",job=\"$jobR\"}) / (node_memory_SwapTotal_bytes{instance=\"$nodeR\",job=\"$jobR\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{instance=\"$nodeR\", job=\"$jobR\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=\"$nodeR\", job=\"$jobR\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=\"$nodeR\", job=\"$jobR\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$nodeR\",job=\"$jobR\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$nodeR\",job=\"$jobR\"} - node_memory_MemFree_bytes{instance=\"$nodeR\",job=\"$jobR\"} - (node_memory_Cached_bytes{instance=\"$nodeR\",job=\"$jobR\"} + node_memory_Buffers_bytes{instance=\"$nodeR\",job=\"$jobR\"} + node_memory_SReclaimable_bytes{instance=\"$nodeR\",job=\"$jobR\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$nodeR\",job=\"$jobR\"} + node_memory_Buffers_bytes{instance=\"$nodeR\",job=\"$jobR\"} + node_memory_SReclaimable_bytes{instance=\"$nodeR\",job=\"$jobR\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$nodeR\",job=\"$jobR\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$nodeR\",job=\"$jobR\"} - node_memory_SwapFree_bytes{instance=\"$nodeR\",job=\"$jobR\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "System load average over 1, 5, and 15 minutes. Reflects the number of active or waiting processes. Values above CPU core count may indicate overload",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 15m"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "CPU Core Count"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "Tx {{device}} "
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "System load average over 1, 5, and 15 minutes. Reflects the number of active or waiting processes. Values above CPU core count may indicate overload",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$nodeR\",job=\"$jobR\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$nodeR\",job=\"$jobR\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$nodeR\",job=\"$jobR\"}",
     "legendFormat": "Load 15m"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$nodeR\",job=\"$jobR\"}) by (cpu))",
     "legendFormat": "CPU Core Count"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$nodeR\",job=\"$jobR\"}[$__rate_interval])*8",
     "legendFormat": "Rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$nodeR\",job=\"$jobR\"}[$__rate_interval])*8",
     "legendFormat": "Tx {{device}} "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": {
    "content": "<h5 style=\"text-align:center;font-size: 3em\">NAS</h5>\r\n\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "options": {
    "content": "---\r\n<p style=\"text-align:center;font-size: 5em\">Remote Cloud</p>\r\n\r\n---\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 61 },
   "options": {
    "content": "<h5 style=\"text-align:center;font-size: 3em\">VPS-MailCow</h5>\r\n\r\n\r\n\r\n"
   }
  },
  {
   "title": "Container Running",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "mailcow_container_running", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mailcow_mailbox_messages", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RSPAMD Action",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (mailcow_rspamd_action)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}