crossplane:
  poolerMode: shared

authentik:
  nameOverride: authentik
  
  authentik:
    log_level: warning
    error_reporting:
      enabled: true

  blueprints:
    configMaps:
      - authentik-custom-blueprints

  postgresql:
    enabled: false

  server:
    env:
      - name: AUTHENTIK_POSTGRESQL__CONN_MAX_AGE
        value: "60"
      - name: AUTHENTIK_POSTGRESQL__DISABLE_SERVER_SIDE_CURSORS
        value: "true"
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: secret-key
      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: endpoint
      - name: AUTHENTIK_POSTGRESQL__PORT
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: port
      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: username
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: password
      - name: AUTHENTIK_POSTGRESQL__NAME
        value: "authentik-db"
      - name: AUTHENTIK_ARGOCD_OIDC_SECRET
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: argocd-oidc-client-secret
      - name: AUTHENTIK_GRAFANA_OIDC_SECRET
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: grafana-oidc-client-secret
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        labels:
          release: kube-prometheus-stack

  worker:
    env:
      - name: AUTHENTIK_POSTGRESQL__CONN_MAX_AGE
        value: "60"
      - name: AUTHENTIK_POSTGRESQL__DISABLE_SERVER_SIDE_CURSORS
        value: "true"
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: secret-key
      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: endpoint
      - name: AUTHENTIK_POSTGRESQL__PORT
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: port
      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: username
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-db-conn
            key: password
      - name: AUTHENTIK_POSTGRESQL__NAME
        value: "authentik-db"
      - name: AUTHENTIK_ARGOCD_OIDC_SECRET
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: argocd-oidc-client-secret
      - name: AUTHENTIK_GRAFANA_OIDC_SECRET
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: grafana-oidc-client-secret
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        labels:
          release: kube-prometheus-stack
