apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/FinnPL/Homelab-Setup.git
    targetRevision: main
    path: charts/kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /spec/admission
        - /spec/emitWarning
      jqPathExpressions:
        - .spec.rules[]?.skipBackgroundRequests
    - group: kyverno.io
      kind: Policy
      jsonPointers:
        - /spec/admission
        - /spec/emitWarning
      jqPathExpressions:
        - .spec.rules[]?.skipBackgroundRequests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
