apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/rancher/local-path-provisioner/charts
    chart: local-path-provisioner
    targetRevision: 0.0.34
    helm:
      valuesObject:
        storageClass:
          name: local-path
          create: true
          defaultClass: false
        tolerations:
          - key: dedicated
            operator: Equal
            value: database
            effect: NoSchedule
        helperPod:
          tolerations:
            - key: dedicated
              operator: Equal
              value: database
              effect: NoSchedule
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /opt/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
