version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik
      - traefik_certificates:/letsencrypt
      - ./traefik/traefik_dynamic_config.yaml:/etc/traefik/dynamic.yaml
    environment:
      - CLOUDFLARE_API_TOKEN=your-api-token
    command:
      - "--api=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yaml"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=your-email@example.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`port.lippok.dev`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"

  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.rule=Host(`gatus.lippok.dev`)"
      - "traefik.http.routers.gatus.entrypoints=websecure"
      - "traefik.http.routers.gatus.tls.certresolver=cloudflare"
    environment:
      - "GATUS_CONFIG_FILE=/config/config.yaml"
    volumes:
      - ./gatus:/config

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`olympus.lippok.dev`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
    volumes:
      - /homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  traefik_data:
  traefik_certificates:
  portainer_data: