apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dns-relay-tls
  namespace: dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: dns-relay-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "relay.lippok.dev"
    - "*.relay.lippok.dev"
