apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: dns
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - 127.0.0.1:5335

    customDNS:
      customTTL: 1h
      # Resolve only via Blocky as Public DNS points this name at 192.0.2.1
      # Serves as simple "Am I using Blocky?" check.
      zone: |
        $TTL 3600
        dns-check.cloud.lippok.dev. IN CNAME oci.cloud.lippok.dev.

    log:
      level: warn
      format: text
      timestamp: true
      privacy: true

    blocking:
      denylists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://adaway.org/hosts.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt
        malware:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif-onlydomains.txt
        native:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.apple-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.amazon-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.samsung-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.huawei-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.xiaomi-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.vivo-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.oppo-realme-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.lgwebos-onlydomains.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.roku-onlydomains.txt

      allowlists:
        ads: &connectivity-checks
          - |
            connectivitycheck.gstatic.com
            clients3.google.com
            msftconnecttest.com
            msftncsi.com
            ping.ui.com
            connectivity.ubnt.com
            www.msftconnecttest.com
            ipv6.msftconnecttest.com
        malware: *connectivity-checks
        native: *connectivity-checks

      clientGroupsBlock:
        default:
          - ads
          - malware
          - native

      blockType: nxDomain
      loading:
        refreshPeriod: 24h
        concurrency: 4
        downloads:
          timeout: 4m
          attempts: 3
          cooldown: 5s

    caching:
      minTime: 5m
      maxTime: 30m
      prefetching: true
      prefetchExpires: 24h
      prefetchThreshold: 3

    prometheus:
      enable: true
      path: /metrics

    ports:
      dns: 53
      http: 4000
      https: 443

    certFile: /tls/tls.crt
    keyFile: /tls/tls.key
