apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: dns
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - 127.0.0.1:5335

    log:
      level: warn
      format: text
      timestamp: true
      privacy: true

    blocking:
      denylists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://adaway.org/hosts.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/pro.txt
        malware:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/tif.txt

      allowlists:
        ads:
          - connectivitycheck.gstatic.com
          - clients3.google.com
          - msftconnecttest.com
          - msftncsi.com
          - ping.ui.com
          - connectivity.ubnt.com
          - www.msftconnecttest.com
          - ipv6.msftconnecttest.com
        malware:
          - connectivitycheck.gstatic.com
          - clients3.google.com
          - msftconnecttest.com
          - msftncsi.com
          - ping.ui.com
          - connectivity.ubnt.com
          - www.msftconnecttest.com
          - ipv6.msftconnecttest.com

      clientGroupsBlock:
        default:
          - ads
          - malware

      blockType: nxDomain
      loading:
        refreshPeriod: 24h
        concurrency: 2
        downloads:
          timeout: 4m
          attempts: 3
          cooldown: 5s

    caching:
      minTime: 5m
      maxTime: 30m
      prefetching: true
      prefetchExpires: 2h
      prefetchThreshold: 5

    prometheus:
      enable: true
      path: /metrics

    ports:
      dns: 53
      http: 4000
