apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocky
  namespace: dns
  labels:
    app: dns
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - dns
  selector:
    matchLabels:
      app: dns
