apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetragon
  namespace: tetragon
  labels:
    app: tetragon
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - tetragon
  selector:
    matchLabels:
      app.kubernetes.io/part-of: tetragon
