apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: oidc.authentik.clientSecret
      remoteRef:
        key: apps/argocd
        property: oidc-client-secret
