apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
    - secretKey: github-token
      remoteRef:
        key: apps/argocd
        property: github-pat
    - secretKey: discord-webhook
      remoteRef:
        key: apps/alertmanager
        property: discord-webhook-url
