apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
    - secretKey: github-token
      remoteRef:
        key: argocd-github-notifications
        property: token
    - secretKey: discord-webhook
      remoteRef:
        key: alertmanager-discord
        property: webhook-url
