apiVersion: v1
kind: ConfigMap
metadata:
  name: it-tools-nginx-logging
  labels:
    app.kubernetes.io/name: it-tools
    app.kubernetes.io/part-of: homelab
{{- $accessLog := default "off" .Values.nginx.accessLog }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        error_log /dev/stderr {{ default "warn" .Values.nginx.errorLogLevel }};
{{- if eq (lower (toString $accessLog)) "off" }}
        access_log off;
{{- else }}
        access_log /dev/stdout {{ $accessLog }};
{{- end }}

        location / {
            try_files $uri $uri/ /index.html;
        }
    }