tetragon:
  crds:
    installMethod: helm

  export:
    # Only to tempfs, no sdcard writes.
    mode: ""

  tetragon:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 384Mi

  tetragonOperator:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
    containerSecurityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
