name: Docker Compose Syntax Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker-compose-syntax:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and Check Docker Compose Syntax
        run: |
          find . -name 'docker-compose.yml' -print0 | while IFS= read -r -d '' file; do
            echo "Checking $file"
            docker compose -f "$file" config
          done