name: Docker Scout PR Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the PR code.
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Install Docker Scout CLI binary manually.
      - name: Install Docker Scout CLI
        run: |
          echo "Downloading Docker Scout CLI binary..."
          curl -fsSL https://github.com/docker/scout-cli/releases/download/latest/docker-scout-linux-amd64 -o docker-scout
          chmod +x docker-scout
          sudo mv docker-scout /usr/local/bin/docker-scout

      # 3. Verify Docker and Docker Scout installation.
      - name: Verify Docker Scout CLI installation
        run: |
          echo "Docker version:"
          docker --version
          echo "Docker Scout version:"
          docker-scout version

      # 4. Find any changed docker-compose files.
      - name: Find changed docker-compose files
        id: find-files
        run: |
          # List changed files between the PR base and current HEAD.
          CHANGED_FILES=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" HEAD | grep -Ei 'docker-compose\.(ya?ml)' || true)
          echo "Found changed docker-compose files:"
          echo "$CHANGED_FILES"
          # Export the file list as an output.
          echo "::set-output name=files::${CHANGED_FILES}"

      # 5. Analyze Docker images and CVEs from the changed files.
      - name: Analyze Docker images in docker-compose files
        id: analyze
        run: |
          OUTPUT_FILE="docker-scout-results.md"
          echo "### Docker Scout Analysis" > $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE
          echo "| Docker Image | Metadata | Open CVEs |" >> $OUTPUT_FILE
          echo "|--------------|----------|-----------|" >> $OUTPUT_FILE

          if [ -z "${{ steps.find-files.outputs.files }}" ]; then
            echo "No docker-compose files changed." >> $OUTPUT_FILE
          else
            for file in ${{ steps.find-files.outputs.files }}; do
              echo "Processing file: $file"
              # Extract image names from lines that define an image.
              IMAGES=$(grep -E '^\s*image:' "$file" | awk '{print $2}')
              for image in $IMAGES; do
                echo "Scanning image: $image"

                # Use the Docker Scout CLI to inspect image metadata.
                METADATA=$(docker-scout inspect "$image" --format '{{json .}}' 2>/dev/null || echo '{}')
                # For demonstration, extract repository and tag using jq (if available).
                SHORT_META=$(echo "$METADATA" | jq -r 'if .Repository and .Tag then "\(.Repository)@\(.Tag)" else "N/A" end' 2>/dev/null)

                # Get open CVEs.
                CVES=$(docker-scout cves "$image" 2>/dev/null || echo "None")
                # Remove newlines from CVES so the Markdown table stays intact.
                CVES=$(echo "$CVES" | tr '\n' ' ')

                # Append a row to the Markdown table.
                echo "| \`$image\` | $SHORT_META | $CVES |" >> $OUTPUT_FILE
              done
            done
          fi
          echo "Docker Scout Analysis:"
          cat $OUTPUT_FILE
          echo "::set-output name=result::$(cat $OUTPUT_FILE)"

      # 6. Post the Markdown table as a comment on the PR.
      - name: Comment on PR with Docker Scout results
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.analyze.outputs.result }}
