name: Minerva - Deploy Docker Compose
on:
    push:
        branches:
            - main
        paths:
            - "minerva/**"
            - ".github/workflows/minerva-deploy.yaml"

jobs:
    deploy:
        runs-on: pi3
        environment: Pi3
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Clear Env File
              run: echo "" > minerva/.env

            - name: Set up Env File
              run: |
                  echo 'TAILSCALE_AUTHKEY=${{ secrets.TAILSCALE_AUTHKEY }}' >> minerva/.env

            - name: Pull latest images
              run: docker compose -f minerva/docker-compose.yml pull

            - name: Stop existing containers
              run: docker compose -f minerva/docker-compose.yml down || true

            - name: Start containers
              run: docker compose -f minerva/docker-compose.yml up -d
