name: "Repo: lint"

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    env:
      # terraform_* handled in terraform-lint; gitleaks handled in security-trivy
      SKIP: terraform_fmt,terraform_validate,terraform_tflint,terraform_trivy,gitleaks
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
